version: "3.4"
services:
  seata-server:
    image: harbor.daishub.com/kangaroo/kangaroo-seata:latest
    hostname: seata-server
    restart: always
    ports:
      - "8091:8091"
    volumes:
      - ./conf/registry.conf:/opt/seata/conf/registry.conf
      - ./conf/file.conf:/opt/seata/conf/file.conf
    environment:
      #      - SEATA_IP=192.168.2.73
      - SEATA_PORT=8091