spring:
  application:
    name: spring-boot-ribbon
  cloud:
    nacos:
      discovery:
        server-addr: 10.50.20.232:8848
        watch-delay: 3000
server:
  port: 8096

feign:
  hystrix:
    enabled: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            #设置请求超时时间，默认1秒，超过指定的时间后，触发服务熔断
            timeoutInMilliseconds: 100